name: Branch Status Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  check-branch-status:
    name: Check Branch Synchronization Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze branch status
        run: |
          echo "🔍 Analyzing branch synchronization status..."
          git fetch origin main develop
          
          MAIN_SHA=$(git rev-parse origin/main)
          DEVELOP_SHA=$(git rev-parse origin/develop)
          
          echo "📊 Branch Status Report"
          echo "======================="
          echo "🌟 Main branch: $MAIN_SHA"
          echo "🚀 Develop branch: $DEVELOP_SHA"
          echo ""
          
          # Check relationship between branches
          if [[ "$MAIN_SHA" == "$DEVELOP_SHA" ]]; then
            echo "✅ Branches are perfectly synchronized"
            echo "::notice::Branches are in sync"
          elif git merge-base --is-ancestor $DEVELOP_SHA $MAIN_SHA; then
            COMMITS_BEHIND=$(git rev-list --count $DEVELOP_SHA..origin/main)
            echo "⬆️ Develop is $COMMITS_BEHIND commits behind main"
            echo "::warning::Develop branch needs to be updated"
            
            echo ""
            echo "📝 Commits that develop is missing:"
            git log --oneline $DEVELOP_SHA..origin/main
          elif git merge-base --is-ancestor $MAIN_SHA $DEVELOP_SHA; then
            COMMITS_AHEAD=$(git rev-list --count origin/main..$DEVELOP_SHA)
            echo "⬇️ Develop is $COMMITS_AHEAD commits ahead of main"
            echo "::notice::Develop has new changes ready for main"
            
            echo ""
            echo "📝 Commits that main is missing:"
            git log --oneline origin/main..$DEVELOP_SHA
          else
            echo "🔀 Branches have diverged - manual intervention may be needed"
            echo "::error::Branches have diverged"
            
            MERGE_BASE=$(git merge-base origin/main origin/develop)
            MAIN_COMMITS=$(git rev-list --count $MERGE_BASE..origin/main)
            DEVELOP_COMMITS=$(git rev-list --count $MERGE_BASE..origin/develop)
            
            echo "📊 Since common ancestor ($MERGE_BASE):"
            echo "   - Main has $MAIN_COMMITS unique commits"
            echo "   - Develop has $DEVELOP_COMMITS unique commits"
          fi
          
          echo ""
          echo "🔧 Recent activity:"
          echo "Main branch (last 3 commits):"
          git log --oneline -3 origin/main
          echo ""
          echo "Develop branch (last 3 commits):"
          git log --oneline -3 origin/develop

      - name: Create sync recommendation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            
            // This would create an issue or comment with sync recommendations
            // For now, we'll just log the status
            console.log('Branch status check completed');
            console.log('Check the workflow logs for detailed branch analysis');